server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth_postgres:5432/authdb
    username: auth_user
    password: "0206"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
